pipeline {
    agent any
    
    stages{
        stage('one'){
            steps{
                echo "first"
            }
        }
        stage('two')
        {
            steps{
                echo "second"
            }
        }
    }
    
    post{
        always{
            echo "pipeline status success"
        }
    }
}
